import type { Metadata } from "next";
import { Gauge, Search, ShieldCheck, Smartphone, TrendingUp } from "lucide-react";
import { AuditForm } from "@/components/ui/AuditForm";
import { JsonLd } from "@/components/seo/JsonLd";
import { jsonLdForPage, pageMetadata } from "@/lib/seo";

export const metadata: Metadata = pageMetadata({
  title: "Free Website Audit Dubai | Speed, SEO & Conversion Check",
  description:
    "Get a free 5-point website audit — speed, mobile experience, SEO, security and conversion. A Dubai full-stack developer reviews your site and replies within 4 hours.",
  path: "/free-website-audit"
});

const points = [
  { icon: Gauge, title: "Speed & Core Web Vitals", text: "Where load time and LCP/CLS/INP are costing you visitors and rankings." },
  { icon: Smartphone, title: "Mobile experience", text: "How the site really performs on phones — the majority of your traffic." },
  { icon: Search, title: "SEO foundations", text: "Indexing, metadata, schema and structure gaps holding back visibility." },
  { icon: TrendingUp, title: "Conversion & UX", text: "Friction points and weak calls-to-action that lose enquiries." },
  { icon: ShieldCheck, title: "Security & tech health", text: "Outdated platform, plugin or hosting risks worth fixing." }
];

// What each headline check actually involves. The five cards above say what is
// looked at; this says how, so someone can judge whether the audit is worth their
// time before handing over a URL.
const detail = [
  {
    title: "Speed & Core Web Vitals",
    body: "Every page is measured, not estimated. Largest Contentful Paint tells you how long before a visitor sees the thing they came for; Cumulative Layout Shift catches content that jumps while loading and makes people mis-tap; Interaction to Next Paint shows whether the page responds when tapped. Alongside those, the real transferred weight of the page is totalled — images served far larger than they render, render-blocking CSS and JavaScript in the head, fonts that hide text while they load, and assets that are re-downloaded on every visit because caching headers are missing."
  },
  {
    title: "Mobile experience",
    body: "Most traffic arrives on a phone, and most sites are still designed on a laptop. The audit checks tap-target spacing, whether text is legible without pinch-zoom, whether anything scrolls sideways, how forms behave with a mobile keyboard open, and how the page holds up on a mid-range Android over a normal mobile connection rather than office Wi-Fi."
  },
  {
    title: "SEO foundations",
    body: "Indexability comes first: robots directives, canonical tags, and whether the sitemap and the pages it lists actually agree. Then titles and meta descriptions — length, uniqueness, and whether they are being truncated in results. Then structured data, checked against what is visible on the page, because markup that describes something a visitor cannot see is ignored at best. Internal linking is mapped too, since pages with no inbound links from your own site are the ones search engines find last."
  },
  {
    title: "Conversion & UX",
    body: "A site can rank and still lose the enquiry. This looks at whether the page answers the question a visitor arrived with, how far down the first call to action sits, how many fields the contact form asks for before someone gives up, whether pricing or process is explained or hidden, and what trust signals — reviews, real work, a named person, a reachable address — are present at the moment someone decides."
  },
  {
    title: "Security & tech health",
    body: "HTTPS and certificate validity, security headers, and whether anything is being served that should not be public — configuration files, logs, backups, directory listings. On WordPress and similar platforms, the core, theme and plugin versions are checked against known advisories, and abandoned plugins are flagged, since an unmaintained plugin is the most common way a small business site gets compromised."
  }
];

const faq = [
  {
    q: "What does it cost, and what is the catch?",
    a: "It is free and there is no obligation. It exists because most enquiries arrive without either side knowing whether there is real work to do. The audit answers that. If the fixes are small enough to do yourself, the reply says so."
  },
  {
    q: "How long does it take?",
    a: "A reply within four hours during working hours. It is written by hand after looking at the site, not generated by a tool the moment the form is submitted."
  },
  {
    q: "Do you need access to my website?",
    a: "No. Everything above is checked from the outside using the public site. Nothing is installed and no logins are needed."
  },
  {
    q: "What do I actually receive?",
    a: "A written reply naming the specific problems found, what each one is costing in plain terms, and which to fix first. Where a number can be measured — page weight, load time, how many pages carry a duplicate title — it is included, so the findings can be verified rather than taken on trust."
  }
];

export default function FreeWebsiteAuditPage() {
  return (
    <>
      <JsonLd data={jsonLdForPage("/free-website-audit")} id="audit-json-ld" />
      <section className="section-pad page-start">
        <div className="mx-auto max-w-7xl px-5">
          <div className="grid items-start gap-10 lg:grid-cols-[1.05fr_0.95fr]">
            <div>
              <p className="inline-flex items-center gap-2 rounded-full border border-emerald/25 bg-emerald/10 px-4 py-1.5 text-xs font-semibold uppercase tracking-[0.18em] text-emerald light:border-emerald-600/25 light:bg-emerald-50 light:text-emerald-700">
                <Search size={14} /> Free · No obligation
              </p>
              <h1 className="mt-5 max-w-[18ch] font-display text-4xl font-semibold leading-[1.05] text-white light:text-slate-950 md:text-5xl">
                Free 5-point website audit
              </h1>
              <p className="mt-5 max-w-xl text-base leading-8 text-silver/82 light:text-slate-600">
                Send your URL and I will personally review your website across speed, mobile, SEO,
                conversion and security — then send back the highest-impact fixes. No automated PDF,
                no sales pressure, reply within 4 hours.
              </p>
              <ul className="mt-8 grid gap-4">
                {points.map(({ icon: Icon, title, text }) => (
                  <li key={title} className="flex gap-3">
                    <span className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl border border-cyan/25 bg-cyan/10 text-cyan light:border-blue-500/25 light:bg-blue-50 light:text-blue-700">
                      <Icon size={17} />
                    </span>
                    <div>
                      <p className="font-display text-sm font-semibold text-white light:text-slate-950">{title}</p>
                      <p className="mt-0.5 text-sm leading-6 text-silver/70 light:text-slate-600">{text}</p>
                    </div>
                  </li>
                ))}
              </ul>
            </div>
            <div className="lg:sticky lg:top-28">
              <AuditForm />
            </div>
          </div>

          <div className="mt-20 max-w-3xl">
            <h2 className="font-display text-2xl font-semibold text-white light:text-slate-950 md:text-3xl">
              What each check actually looks at
            </h2>
            <p className="mt-4 text-base leading-8 text-silver/78 light:text-slate-600">
              Plenty of “free audits” are a tool’s PDF with a colour-coded score and no
              judgement attached. This is the opposite: each area below is checked by hand,
              and the reply tells you which findings matter for your site and which are noise.
            </p>

            <div className="mt-10 grid gap-8">
              {detail.map(({ title, body }) => (
                <div key={title}>
                  <h3 className="font-display text-lg font-semibold text-white light:text-slate-950">{title}</h3>
                  <p className="mt-3 text-[15px] leading-8 text-silver/74 light:text-slate-600">{body}</p>
                </div>
              ))}
            </div>

            <h2 className="mt-16 font-display text-2xl font-semibold text-white light:text-slate-950 md:text-3xl">
              Common questions
            </h2>
            <div className="mt-8 grid gap-7">
              {faq.map(({ q, a }) => (
                <div key={q}>
                  <h3 className="font-display text-base font-semibold text-white light:text-slate-950">{q}</h3>
                  <p className="mt-2.5 text-[15px] leading-8 text-silver/74 light:text-slate-600">{a}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
