/**
 * RSS feed generator for anastanveer.com blog.
 * Run: node scripts/generate-rss.mjs
 * Also runs automatically via "prebuild" script.
 *
 * POSTS array mirrors data/site.ts blogs — update both when adding posts.
 */

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const SITE_URL = "https://anastanveer.com";
const FEED_TITLE = "Anas Tanveer — Web Development Blog";
const FEED_DESC =
  "Decision-focused articles on Laravel, WordPress, Shopify, website speed, technical SEO, ecommerce, dashboards and business systems for Dubai, UK and Canadian businesses.";
const AUTHOR_EMAIL = "info@anastanveer.com";
const AUTHOR_NAME = "Anas Tanveer";

const POSTS = [
  { slug: "choose-laravel-instead-of-plugin", title: "When to Choose Laravel Instead of a Plugin", excerpt: "A practical guide for companies that need dashboards, portals, ERP workflows, API integrations, or scalable backend logic.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "Laravel", image: "/images/blog/blog-1-hd.webp" },
  { slug: "wordpress-vs-custom-laravel", title: "WordPress vs Laravel: Choosing the Right Web Solution", excerpt: "How to decide between a marketing website, CMS, custom platform, dashboard, or long-term business system.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "Strategy", image: "/images/about-resume-brand.webp" },
  { slug: "shopify-conversion-fixes", title: "Shopify Conversion Fixes That Reduce Customer Doubt", excerpt: "Practical improvements for product pages, size selectors, mobile UX, trust signals, speed, and checkout confidence.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "Shopify", image: "/images/projects-suite-520.webp" },
  { slug: "website-speed-checklist-before-ads", title: "Website Speed Checklist Before Running Ads", excerpt: "A technical checklist for Core Web Vitals, image weight, scripts, caching, hosting, SEO readiness, and mobile UX.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "Performance", image: "/images/contact-pricing.webp" },
  { slug: "seo-friendly-development-before-marketing", title: "Why SEO-Friendly Development Starts Before Marketing", excerpt: "Why schema, speed, clean headings, service pages, metadata, internal links, and crawlable content matter before campaigns.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "SEO", image: "/images/services-architecture-520.webp" },
  { slug: "ai-search-seo-dubai-businesses", title: "AI Search SEO for Dubai Business Websites", excerpt: "How businesses can prepare websites for AI-assisted search with clear service pages, helpful answers, schema, speed and trust signals.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "AI SEO", image: "/images/anas-premium-hero-1100.webp" },
  { slug: "ai-chatbots-laravel-wordpress-shopify", title: "AI Chatbots for Laravel, WordPress and Shopify", excerpt: "A practical guide to AI chatbot and automation ideas for lead qualification, support, product questions and internal workflows.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "AI Automation", image: "/images/projects-suite-520.webp" },
  { slug: "ai-website-audit-speed-seo-conversion", title: "AI Website Audit for Speed, SEO and Conversion", excerpt: "How an AI-assisted website audit can help find slow pages, weak SEO structure, confusing UX and conversion blockers before they cost leads.", publishedAt: "2026-04-30", updatedAt: "2026-04-30", tag: "AI Audit", image: "/images/contact-pricing.webp" },
  { slug: "hire-laravel-developer-guide", title: "How to Hire a Laravel Developer: Full Checklist for Business Owners", excerpt: "A practical guide for business owners, agencies and recruiters on what to look for when hiring a Laravel developer for custom web applications, dashboards and platforms.", publishedAt: "2026-05-10", updatedAt: "2026-05-13", tag: "Laravel", image: "/images/services-architecture-520.webp" },
  { slug: "remote-full-stack-developer-vs-agency", title: "Remote Full Stack Developer vs Local Agency: Which Is Better?", excerpt: "How to decide between hiring a remote full stack developer, a local agency or a dedicated offshore team for your next web project.", publishedAt: "2026-05-10", updatedAt: "2026-05-13", tag: "Strategy", image: "/images/about-resume-brand.webp" },
  { slug: "shopify-developer-for-hire-checklist", title: "Shopify Developer for Hire: Checklist for Store Owners", excerpt: "What to look for when you hire a Shopify developer — theme work, Liquid, app integration, conversion focus and post-launch support.", publishedAt: "2026-05-11", updatedAt: "2026-05-13", tag: "Shopify", image: "/images/projects-suite-520.webp" },
  { slug: "custom-business-dashboard-development", title: "Custom Business Dashboard Development: When You Need One", excerpt: "A guide to deciding when a custom Laravel dashboard is better than off-the-shelf tools, and how to plan the development the right way.", publishedAt: "2026-05-11", updatedAt: "2026-05-13", tag: "Laravel", image: "/images/contact-pricing.webp" },
  { slug: "wordpress-developer-for-hire-guide", title: "WordPress Developer for Hire: Freelancer vs Agency vs Dedicated Dev", excerpt: "How to choose the right type of WordPress developer for your project — business website, WooCommerce store, speed optimization or ongoing maintenance.", publishedAt: "2026-05-12", updatedAt: "2026-05-13", tag: "WordPress", image: "/images/services-architecture-520.webp" },
  { slug: "web-application-development-services-guide", title: "Web Application Development Services: Planning Your First Custom Platform", excerpt: "A practical guide for business owners and founders planning their first custom web application — from requirements to architecture to launch.", publishedAt: "2026-05-12", updatedAt: "2026-05-13", tag: "Strategy", image: "/images/about-resume-brand.webp" },
  { slug: "web-developer-for-hire", title: "Web Developer for Hire: Complete Guide for Business Owners", excerpt: "A complete guide to hiring a web developer — what skills matter, how to evaluate portfolios, compare rates and avoid costly mistakes.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Strategy", image: "/images/services-architecture-520.webp" },
  { slug: "hire-web-developer-for-business", title: "How to Hire a Web Developer for Your Business", excerpt: "Compare the three main options for hiring a web developer and choose the right engagement type for your project size, timeline and budget.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Strategy", image: "/images/about-resume-brand.webp" },
  { slug: "saas-web-application-developer", title: "SaaS Web Application Developer: Plan Your First SaaS Platform", excerpt: "A founder-focused guide to finding the right SaaS developer and planning a web application that can grow without rebuilding from zero.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Laravel", image: "/images/projects-suite-520.webp" },
  { slug: "php-developer-for-hire", title: "PHP Developer for Hire: What to Check Before You Hire", excerpt: "How to evaluate a PHP developer before hiring — code structure, security knowledge, framework experience, API skills and long-term maintainability.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Laravel", image: "/images/contact-pricing.webp" },
  { slug: "ecommerce-website-developer-for-hire", title: "Ecommerce Website Developer for Hire: Guide for Store Owners", excerpt: "How to hire the right ecommerce developer for Shopify, WooCommerce or custom platforms — and what questions reveal real conversion expertise.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Shopify", image: "/images/projects-suite-520.webp" },
  { slug: "website-speed-optimization-services", title: "Website Speed Optimization Services: What You're Paying For", excerpt: "What real website speed optimization services include — Core Web Vitals, image compression, script management, hosting, caching and what to expect from results.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Performance", image: "/images/contact-pricing.webp" },
  { slug: "erp-software-development-guide", title: "ERP Software Development: Custom Build vs Off-the-Shelf Guide", excerpt: "A practical guide for operations directors and founders on when to choose custom ERP development over SaaS tools and how to plan the build correctly.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Laravel", image: "/images/about-resume-brand.webp" },
  { slug: "how-to-choose-web-developer", title: "How to Choose a Web Developer: Questions Before You Hire", excerpt: "A practical framework for choosing the right web developer for your specific project — what questions to ask, what answers to look for and what red flags to avoid.", publishedAt: "2026-05-13", updatedAt: "2026-05-13", tag: "Strategy", image: "/images/services-architecture-520.webp" },
  { slug: "nextjs-developer-for-hire", title: "Next.js Developer for Hire: When and Why", excerpt: "A practical breakdown of when Next.js is the right choice for your web project and what to look for when hiring a Next.js developer.", publishedAt: "2026-05-15", updatedAt: "2026-05-27", tag: "Next.js", image: "/images/blog/blog-2-hd.webp" },
  { slug: "laravel-vs-nodejs", title: "Laravel vs Node.js: Which Backend for Your Business Project", excerpt: "A direct comparison of Laravel and Node.js for business web applications — covering speed, cost, team requirements and when each makes sense.", publishedAt: "2026-05-18", updatedAt: "2026-05-18", tag: "Laravel", image: "/images/blog/blog-5-hd.webp" },
  { slug: "freelance-web-developer-dubai", title: "Freelance Web Developer Dubai: Rates, Hiring Guide and Expectations", excerpt: "A guide for Dubai businesses considering a freelance web developer — covering rates, expectations, risks and how to structure the engagement.", publishedAt: "2026-05-21", updatedAt: "2026-05-21", tag: "Hiring", image: "/images/blog/blog-8-hd.webp" },
  { slug: "laravel-api-development", title: "Laravel API Development: Scalable REST APIs for Business", excerpt: "A practical guide to building production REST APIs with Laravel — covering structure, authentication, versioning and performance for real business applications.", publishedAt: "2026-05-24", updatedAt: "2026-05-24", tag: "Laravel", image: "/images/blog/blog-11-hd.webp" },
  { slug: "shopify-custom-theme-development", title: "Shopify Custom Theme Development: Cost and When to Invest", excerpt: "A clear breakdown of when a custom Shopify theme is worth the cost versus using a premium template, and what the development process involves.", publishedAt: "2026-05-27", updatedAt: "2026-05-30", tag: "Shopify", image: "/images/blog/blog-6-hd.webp" },
  { slug: "web-app-vs-website", title: "Web App vs Website: Which Does Your Business Need", excerpt: "A practical guide for business owners deciding between a marketing website and a web application — what each does and when you need which.", publishedAt: "2026-05-30", updatedAt: "2026-06-02", tag: "Web Development", image: "/images/blog/blog-7-hd.webp" },
  { slug: "api-integration-services", title: "API Integration Services: Business Guide to Cost and Planning", excerpt: "A practical guide to API integration for business owners — what it costs, how long it takes, and what can go wrong if not planned correctly.", publishedAt: "2026-06-02", updatedAt: "2026-06-14", tag: "API", image: "/images/blog/blog-4-hd.webp" },
  { slug: "wordpress-speed-optimization", title: "WordPress Speed Optimization: Developer Guide to Real Gains", excerpt: "A technical guide to WordPress speed optimisation covering hosting, caching, images, plugins and Core Web Vitals without breaking your site.", publishedAt: "2026-06-05", updatedAt: "2026-06-08", tag: "WordPress", image: "/images/blog/blog-9-hd.webp" },
  { slug: "ecommerce-shopify-vs-woocommerce", title: "Shopify vs WooCommerce: Ecommerce Comparison for Growing Businesses", excerpt: "A direct comparison of Shopify and WooCommerce for businesses planning an ecommerce build — covering cost, control, speed and long-term ownership.", publishedAt: "2026-06-08", updatedAt: "2026-06-11", tag: "Ecommerce", image: "/images/blog/blog-10-hd.webp" },
  { slug: "react-developer-for-hire", title: "React Developer for Hire: Skills That Matter for Business", excerpt: "A clear guide for businesses evaluating React developers — what to test, what to ignore, and how to match skills to your actual project needs.", publishedAt: "2026-06-11", updatedAt: "2026-06-05", tag: "React", image: "/images/blog/blog-3-hd.webp" },
  { slug: "web-developer-london-guide", title: "Web Developer London: Hiring Guide for London Businesses", excerpt: "What London businesses actually need to know before hiring a web developer — from rates and engagement types to evaluating portfolios and structuring the project brief.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-8-hd.webp" },
  { slug: "laravel-developer-uk-guide", title: "Laravel Developer UK: Hiring Guide for British Businesses", excerpt: "A practical guide for UK businesses and agencies hiring a Laravel developer — covering what to test, what rates to expect, and how to avoid the most common hiring mistakes.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Laravel", image: "/images/blog/blog-1-hd.webp" },
  { slug: "shopify-developer-canada-guide", title: "Shopify Developer Canada: Hiring Guide for Canadian Businesses", excerpt: "How Canadian businesses should hire a Shopify developer — covering what to evaluate, Canadian tax configuration, payment gateways and what to expect from rates in CAD.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Shopify", image: "/images/blog/blog-6-hd.webp" },
  { slug: "web-developer-manchester-guide", title: "Web Developer Manchester: North West UK Hiring Guide", excerpt: "What Manchester and North West UK businesses need to know before hiring a web developer — rates, what to expect from local agencies vs remote developers, and how to structure your project.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-7-hd.webp" },
  { slug: "wordpress-developer-uk-guide", title: "WordPress Developer UK: Hiring Guide for British Businesses", excerpt: "A clear guide for UK businesses hiring a WordPress developer — covering UK rates in GBP, what to test, common mistakes, and when WordPress is (and isn't) the right platform choice.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "WordPress", image: "/images/blog/blog-2-hd.webp" },
  { slug: "shopify-developer-uk-guide", title: "Shopify Developer UK: Hiring Guide for British Store Owners", excerpt: "How UK businesses should hire a Shopify developer — covering GBP rates, UK tax configuration, payment gateways, Shopify 2.0 theme requirements and what to evaluate before signing.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Shopify", image: "/images/blog/blog-9-hd.webp" },
  { slug: "web-developer-birmingham-guide", title: "Web Developer Birmingham: West Midlands Hiring Guide", excerpt: "What Birmingham and West Midlands businesses need to know before hiring a web developer — rates, platform choices, local vs remote, and how to structure your project for a clean outcome.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-10-hd.webp" },
  { slug: "web-developer-uk-cities-guide", title: "Web Developer UK Cities: London, Manchester, Birmingham, Leeds, Glasgow and More", excerpt: "A comprehensive guide to hiring web developers across UK cities — comparing rates, demand, remote vs local, and what each regional market looks for in a developer.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-11-hd.webp" },
  { slug: "web-developer-canada-cities-guide", title: "Web Developer Canada Cities: Toronto, Vancouver, Calgary, Ottawa and Montreal", excerpt: "A comprehensive guide to hiring web developers across Canadian cities — comparing CAD rates, what each province needs, and how remote delivery works for Canadian businesses.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-8-hd.webp" },
  { slug: "nextjs-developer-uk-guide", title: "Next.js Developer UK: What British Businesses Need to Know", excerpt: "A practical guide for UK businesses considering Next.js — covering App Router architecture, why it outperforms plain React for SEO, UK developer rates in GBP, and what to test before hiring.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "React", image: "/images/blog/blog-2-hd.webp" },
  { slug: "fullstack-developer-canada-guide", title: "Full Stack Developer Canada: What Canadian Businesses Need to Know", excerpt: "A practical guide for Canadian businesses hiring a full stack developer — covering what full stack means, CAD rates across Toronto, Vancouver, Calgary and Ottawa, and what to test before hiring.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-11-hd.webp" },
  { slug: "web-developer-leeds-guide", title: "Web Developer Leeds: Yorkshire Hiring Guide for Businesses", excerpt: "What Leeds and Yorkshire businesses need to know before hiring a web developer — GBP rates, agency vs freelancer, platform choices, and how to structure a project for a clean outcome.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-5-hd.webp" },
  { slug: "web-developer-glasgow-guide", title: "Web Developer Glasgow: Scotland Hiring Guide for Businesses", excerpt: "What Glasgow and Scottish businesses need to know before hiring a web developer — GBP rates, Scottish market specifics, platform choices, and how to evaluate developers for your project.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-6-hd.webp" },
  { slug: "web-developer-edinburgh-guide", title: "Web Developer Edinburgh: Scottish Capital Hiring Guide", excerpt: "What Edinburgh businesses need to know before hiring a web developer — GBP rates, financial services and tourism sector requirements, and how to evaluate and structure your project.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-7-hd.webp" },
  { slug: "web-developer-bristol-guide", title: "Web Developer Bristol: South West UK Hiring Guide", excerpt: "What Bristol and South West UK businesses need to know before hiring a web developer — GBP rates, creative and tech sector specifics, platform choices, and what to evaluate before signing.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-8-hd.webp" },
  { slug: "web-developer-sheffield-guide", title: "Web Developer Sheffield: Steel City Hiring Guide for Businesses", excerpt: "What Sheffield and South Yorkshire businesses need to know before hiring a web developer — GBP rates, manufacturing and creative sector requirements, and how to evaluate developers.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-9-hd.webp" },
  { slug: "web-developer-toronto-guide", title: "Web Developer Toronto: Ontario Hiring Guide for Businesses", excerpt: "What Toronto and Ontario businesses need to know before hiring a web developer — CAD rates, Toronto's tech market, Ontario HST, CASL compliance, and how to structure your project.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-1-hd.webp" },
  { slug: "web-developer-vancouver-guide", title: "Web Developer Vancouver: BC Hiring Guide for Businesses", excerpt: "What Vancouver and British Columbia businesses need to know before hiring a web developer — CAD rates, BC PST, CASL, gaming sector specifics, and how to structure your project.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-2-hd.webp" },
  { slug: "web-developer-calgary-guide", title: "Web Developer Calgary: Alberta Hiring Guide for Businesses", excerpt: "What Calgary and Alberta businesses need to know before hiring a web developer — CAD rates, Alberta GST-only tax, energy sector requirements, and how to evaluate developers.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-3-hd.webp" },
  { slug: "web-developer-ottawa-guide", title: "Web Developer Ottawa: Ontario Capital Hiring Guide", excerpt: "What Ottawa and National Capital Region businesses need to know before hiring a web developer — CAD rates, government compliance, bilingual requirements, and how to evaluate developers.", publishedAt: "2026-06-14", updatedAt: "2026-06-14", tag: "Strategy", image: "/images/blog/blog-4-hd.webp" },
  { slug: "nextjs-developer-canada-guide", title: "Next.js Developer Canada: What Canadian Businesses Need to Know", excerpt: "Why Canadian businesses are choosing Next.js over WordPress — covering App Router architecture, Core Web Vitals, headless CMS integration, and Canadian developer rates in CAD.", publishedAt: "2026-06-17", updatedAt: "2026-06-17", tag: "React", image: "/images/blog/blog-3-hd.webp" },
  { slug: "web-developer-montreal-guide", title: "Web Developer Montreal: Quebec Hiring Guide for Businesses", excerpt: "What Montreal and Quebec businesses need to know before hiring a web developer — CAD rates, bilingual requirements, Quebec QST tax, and how to evaluate developers for Quebec-specific projects.", publishedAt: "2026-06-21", updatedAt: "2026-06-21", tag: "Strategy", image: "/images/blog/blog-10-hd.webp" },
  { slug: "web-developer-edmonton-guide", title: "Web Developer Edmonton: Alberta Capital Hiring Guide", excerpt: "What Edmonton and Northern Alberta businesses need to know before hiring a web developer — CAD rates, government compliance, energy sector requirements, and Alberta GST configuration.", publishedAt: "2026-06-21", updatedAt: "2026-06-21", tag: "Strategy", image: "/images/blog/blog-11-hd.webp" },
  { slug: "web-developer-australia-cities-guide", title: "Web Developer Australia Cities: Sydney, Melbourne, Brisbane, Perth, Adelaide", excerpt: "Comprehensive guide to hiring web developers across Australian cities — AUD rates, state-specific sector requirements, and how remote delivery works for Australian businesses.", publishedAt: "2026-06-21", updatedAt: "2026-06-21", tag: "Strategy", image: "/images/blog/blog-8-hd.webp" },
  { slug: "web-developer-australia-guide", title: "Web Developer Australia: Hiring Guide for Australian Businesses", excerpt: "What Australian businesses need to know before hiring a web developer — AUD rates, Australian GST configuration, Privacy Act compliance, Afterpay integration, and how to structure your project.", publishedAt: "2026-06-21", updatedAt: "2026-06-21", tag: "Strategy", image: "/images/blog/blog-1-hd.webp" },
  { slug: "web-developer-sydney-guide", title: "Web Developer Sydney: NSW Hiring Guide for Businesses", excerpt: "What Sydney and NSW businesses need to know before hiring a web developer — AUD rates, financial services requirements, Afterpay, ABN invoicing, and how to evaluate developers for Sydney projects.", publishedAt: "2026-07-01", updatedAt: "2026-07-01", tag: "Strategy", image: "/images/blog/blog-2-hd.webp" },
  { slug: "web-developer-melbourne-guide", title: "Web Developer Melbourne: Victoria Hiring Guide for Businesses", excerpt: "What Melbourne and Victorian businesses need to know before hiring a web developer — AUD rates, design-forward requirements, BNPL payment gateways, hospitality integrations, and how to structure your project.", publishedAt: "2026-07-05", updatedAt: "2026-07-05", tag: "Strategy", image: "/images/blog/blog-3-hd.webp" },
  { slug: "nextjs-developer-australia-guide", title: "Next.js Developer Australia: What Australian Businesses Need to Know", excerpt: "Why Australian businesses choose Next.js over WordPress for google.com.au rankings — App Router, Core Web Vitals, headless Shopify with Next.js, and AUD rate benchmarks.", publishedAt: "2026-07-08", updatedAt: "2026-07-08", tag: "React", image: "/images/blog/blog-2-hd.webp" },
  { slug: "react-developer-australia-guide", title: "React Developer Australia: Hiring Guide for Australian Businesses", excerpt: "How Australian businesses should hire a React developer — TypeScript requirements, WCAG 2.1 AA compliance, AUD rate benchmarks, and when to choose React vs Next.js.", publishedAt: "2026-07-08", updatedAt: "2026-07-08", tag: "React", image: "/images/blog/blog-3-hd.webp" },
  { slug: "web-developer-australia-cities-guide", title: "Web Developer Australia Cities: Sydney, Melbourne, Brisbane, Perth, Adelaide", excerpt: "Comprehensive guide to hiring web developers across Australian cities — AUD rates, state-specific sector requirements, and how remote delivery works for Australian businesses.", publishedAt: "2026-07-12", updatedAt: "2026-07-12", tag: "Strategy", image: "/images/blog/blog-8-hd.webp" },
  { slug: "web-developer-brisbane-guide", title: "Web Developer Brisbane: Queensland Hiring Guide for Businesses", excerpt: "What Brisbane and Queensland businesses need to know before hiring a web developer — AUD rates, construction and tourism sectors, Australian GST, and how to structure your project.", publishedAt: "2026-07-12", updatedAt: "2026-07-12", tag: "Strategy", image: "/images/blog/blog-4-hd.webp" },
  { slug: "web-developer-perth-guide", title: "Web Developer Perth: Western Australia Hiring Guide for Businesses", excerpt: "What Perth and WA businesses need to know before hiring a web developer — AUD rates, mining and resources sector, AWST timezone, and how to evaluate developers for WA projects.", publishedAt: "2026-07-15", updatedAt: "2026-07-15", tag: "Strategy", image: "/images/blog/blog-5-hd.webp" },
  { slug: "shopify-developer-australia-guide", title: "Shopify Developer Australia: Hiring Guide for Australian Store Owners", excerpt: "How Australian businesses should hire a Shopify developer — Australian GST (10%), Afterpay, Australia Post, google.com.au SEO, and AUD rate benchmarks.", publishedAt: "2026-07-19", updatedAt: "2026-07-19", tag: "Shopify", image: "/images/blog/blog-6-hd.webp" },
  { slug: "laravel-developer-australia-guide", title: "Laravel Developer Australia: What Australian Businesses Need to Know", excerpt: "Why Australian businesses choose Laravel for custom web applications — Privacy Act compliance, AWS Sydney hosting, AUD invoicing modules, ABN validation, and how to evaluate Laravel developers in Australia.", publishedAt: "2026-07-22", updatedAt: "2026-07-22", tag: "Laravel", image: "/images/blog/blog-7-hd.webp" },
  { slug: "wordpress-developer-australia-guide", title: "WordPress Developer Australia: Hiring Guide for Australian Businesses", excerpt: "How Australian businesses should hire a WordPress developer — Australian GST in WooCommerce, Privacy Act compliance, Afterpay, Australia Post, and AUD rate benchmarks.", publishedAt: "2026-07-26", updatedAt: "2026-07-26", tag: "WordPress", image: "/images/blog/blog-9-hd.webp" },
  { slug: "fullstack-developer-australia-guide", title: "Full Stack Developer Australia: What Australian Businesses Need to Know", excerpt: "Why Australian businesses hire full stack developers — Laravel + React/Next.js, Privacy Act compliance, AWS Sydney, AUD invoicing modules, and what to evaluate before hiring.", publishedAt: "2026-08-30", updatedAt: "2026-08-30", tag: "Strategy", image: "/images/blog/blog-10-hd.webp" },
  { slug: "web-developer-adelaide-guide", title: "Web Developer Adelaide: South Australia Hiring Guide for Businesses", excerpt: "What Adelaide and SA businesses need to know before hiring a web developer — AUD rates, Adelaide's defence and healthcare sectors, food and wine ecommerce, and how to evaluate developers.", publishedAt: "2026-09-02", updatedAt: "2026-09-02", tag: "Strategy", image: "/images/blog/blog-11-hd.webp" },
  { slug: "react-developer-uk-guide", title: "React Developer UK: What British Businesses Need to Know", excerpt: "How UK businesses should hire a React developer — TypeScript requirements, WCAG 2.1 AA compliance, GBP rate benchmarks, and when to choose React vs Next.js for a UK project.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "React", image: "/images/blog/blog-3-hd.webp" },
  { slug: "fullstack-developer-london-guide", title: "Full Stack Developer London: Hiring Guide for London Businesses", excerpt: "What London businesses need to know before hiring a full stack developer — GBP rates, London's tech market, Laravel + React/Next.js, and how to structure your project.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Strategy", image: "/images/blog/blog-4-hd.webp" },
  { slug: "php-developer-uk-guide", title: "PHP Developer UK: What British Businesses Need to Know", excerpt: "Why UK businesses choose PHP and Laravel for custom web applications — GBP rate benchmarks, UK GDPR compliance, UK VAT configuration, and how to evaluate PHP developers.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Laravel", image: "/images/blog/blog-5-hd.webp" },
  { slug: "laravel-developer-london-guide", title: "Laravel Developer London: Hiring Guide for London Businesses", excerpt: "What London businesses need to know before hiring a Laravel developer — GBP rates, UK GDPR compliance, London financial services requirements, and how to evaluate Laravel developers for London projects.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Laravel", image: "/images/blog/blog-1-hd.webp" },
  { slug: "wordpress-developer-london-guide", title: "WordPress Developer London: Hiring Guide for London Businesses", excerpt: "What London businesses need to know before hiring a WordPress developer — GBP rates, UK GDPR cookie consent, WooCommerce UK VAT, Gutenberg block development, and how to evaluate WordPress developers in London.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "WordPress", image: "/images/blog/blog-2-hd.webp" },
  { slug: "shopify-developer-london-guide", title: "Shopify Developer London: Hiring Guide for London Store Owners", excerpt: "What London businesses need to know before hiring a Shopify developer — GBP rates, UK VAT configuration, post-Brexit EU markets, London fashion and luxury requirements, and how to evaluate Shopify developers in London.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Shopify", image: "/images/blog/blog-6-hd.webp" },
  { slug: "laravel-developer-canada-guide", title: "Laravel Developer Canada: What Canadian Businesses Need to Know", excerpt: "Why Canadian businesses choose Laravel for custom web applications — CASL compliance, Canadian GST/HST invoicing, AWS Canada hosting, and how to evaluate Laravel developers for Canadian projects.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Laravel", image: "/images/blog/blog-7-hd.webp" },
  { slug: "react-developer-canada-guide", title: "React Developer Canada: What Canadian Businesses Need to Know", excerpt: "How Canadian businesses should hire a React developer — TypeScript requirements, CASL compliance, CAD rate benchmarks, and when to choose React vs Next.js for a Canadian project.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "React", image: "/images/blog/blog-3-hd.webp" },
  { slug: "wordpress-developer-canada-guide", title: "WordPress Developer Canada: Hiring Guide for Canadian Businesses", excerpt: "How Canadian businesses should hire a WordPress developer — Canadian GST/HST in WooCommerce, CASL compliance, CAD rates, and how to evaluate WordPress developers for Canadian projects.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "WordPress", image: "/images/blog/blog-9-hd.webp" },
  { slug: "php-developer-canada-guide", title: "PHP Developer Canada: What Canadian Businesses Need to Know", excerpt: "Why Canadian businesses choose PHP and Laravel for custom web applications — CASL compliance, Canadian GST/HST invoicing, CAD rate benchmarks, and how to evaluate PHP developers for Canadian projects.", publishedAt: "2026-07-29", updatedAt: "2026-07-29", tag: "Laravel", image: "/images/blog/blog-5-hd.webp" },
];

const today = new Date().toISOString().slice(0, 10);
const published = POSTS.filter((p) => p.publishedAt <= today).sort(
  (a, b) => b.publishedAt.localeCompare(a.publishedAt)
);

function escapeXml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function rfc822(dateStr) {
  return new Date(dateStr).toUTCString();
}

const items = published
  .map(
    (p) => `
  <item>
    <title>${escapeXml(p.title)}</title>
    <link>${SITE_URL}/blog/${p.slug}/</link>
    <guid isPermaLink="true">${SITE_URL}/blog/${p.slug}/</guid>
    <description>${escapeXml(p.excerpt)}</description>
    <pubDate>${rfc822(p.publishedAt)}</pubDate>
    <lastBuildDate>${rfc822(p.updatedAt)}</lastBuildDate>
    <category>${escapeXml(p.tag)}</category>
    <author>${AUTHOR_EMAIL} (${AUTHOR_NAME})</author>
    <enclosure url="${SITE_URL}${p.image}" type="image/webp" length="0" />
  </item>`
  )
  .join("\n");

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
  xmlns:atom="http://www.w3.org/2005/Atom"
  xmlns:content="http://purl.org/rss/1.0/modules/content/"
  xmlns:dc="http://purl.org/dc/elements/1.1/">
  <channel>
    <title>${escapeXml(FEED_TITLE)}</title>
    <link>${SITE_URL}/blog/</link>
    <description>${escapeXml(FEED_DESC)}</description>
    <language>en-ae</language>
    <managingEditor>${AUTHOR_EMAIL} (${AUTHOR_NAME})</managingEditor>
    <webMaster>${AUTHOR_EMAIL} (${AUTHOR_NAME})</webMaster>
    <lastBuildDate>${rfc822(published[0]?.updatedAt ?? new Date().toISOString())}</lastBuildDate>
    <atom:link href="${SITE_URL}/feed.xml" rel="self" type="application/rss+xml" />
    <image>
      <url>${SITE_URL}/images/anas-premium-hero.webp</url>
      <title>${escapeXml(FEED_TITLE)}</title>
      <link>${SITE_URL}/blog/</link>
    </image>
    ${items}
  </channel>
</rss>`;

const outPath = join(ROOT, "public", "feed.xml");
writeFileSync(outPath, xml.trim(), "utf-8");
console.log(`✓ RSS feed generated → public/feed.xml (${published.length} posts)`);
